server:
  port: 8080
  error:
    include-exception: true
spring:
  application:
    name: msgw-scg
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      httpclient:
        # The connect timeout in millis, the default is 45s.
        connectTimeout: 200
        responseTimeout: 10s
    consul:
        enabled: true
        scheme: HTTP

logging:
  file: /tsf-demo-logs/${spring.application.name}/root.log
  level:
    root: INFO